<wsdl:definitions
     name="dbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AtradiusUtilityApplication/DashboardServices/dbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AtradiusUtilityApplication/DashboardServices/dbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbReference_plt" >
    <plt:role name="dbReference_role" >
      <plt:portType name="tns:dbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbReference" schemaLocation="../Schemas/dbReference.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="dbReferenceInput_msg">
        <wsdl:part name="dbReferenceInput_msg" element="db:dbReferenceInput"/>
    </wsdl:message>
    <wsdl:message name="dbReferenceOutputCollection_msg">
        <wsdl:part name="dbReferenceOutputCollection" element="db:dbReferenceOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbReference_ptt">
        <wsdl:operation name="dbReference">
            <wsdl:input message="tns:dbReferenceInput_msg"/>
            <wsdl:output message="tns:dbReferenceOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
