<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://xmlns.oracle.com/bpel/workflow/taskQueryService" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:task="http://xmlns.oracle.com/bpel/workflow/task"
                xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
                xmlns:ns2="http://xmlns.oracle.com/bpel/workflow/taskError"
                xmlns:ns3="http://xmlns.oracle.com/bpel/workflow/taskQueryService/schema"
                xmlns:common="http://xmlns.oracle.com/bpel/workflow/common"
                xmlns:user="http://xmlns.oracle.com/bpel/workflow/userMetadata"
                xmlns:ns1="http://xmlns.oracle.com/bpel/workflow/taskQuery"
                xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
                xmlns:ns4="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns5="http://xmlns.oracle.com/bpel/workflow/common/tsc">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/TaskQueryService_WSDL_TaskQueryServiceInterface.wsdl"/>
            <oracle-xsl-mapper:rootElement name="taskListRequest" namespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/TaskQueryService_WSDL_TaskQueryServiceInterface.wsdl"/>
            <oracle-xsl-mapper:rootElement name="taskListRequest" namespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [SAT SEP 02 07:22:33 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:taskListRequest>
         <common:workflowContext>
            <common:credential>
               <common:login>
                  <xsl:value-of select="/ns0:taskListRequest/common:workflowContext/common:credential/common:login"/>
               </common:login>
               <common:password>
                  <xsl:value-of select="/ns0:taskListRequest/common:workflowContext/common:credential/common:password"/>
               </common:password>
            </common:credential>
         </common:workflowContext>
         <ns1:taskPredicateQuery startRow="{/ns0:taskListRequest/ns1:taskPredicateQuery/@startRow}"
                                 endRow="{/ns0:taskListRequest/ns1:taskPredicateQuery/@endRow}">
            <ns1:displayColumnList>
               <ns1:displayColumn>
                  <xsl:value-of select="/ns0:taskListRequest/ns1:taskPredicateQuery/ns1:displayColumnList/ns1:displayColumn"/>
               </ns1:displayColumn>
            </ns1:displayColumnList>
            <ns1:optionalInfoList>
               <ns1:taskOptionalInfo>
                  <xsl:value-of select="/ns0:taskListRequest/ns1:taskPredicateQuery/ns1:optionalInfoList/ns1:taskOptionalInfo"/>
               </ns1:taskOptionalInfo>
            </ns1:optionalInfoList>
            <ns1:predicate>
               <ns1:assignmentFilter>
                  <xsl:value-of select="/ns0:taskListRequest/ns1:taskPredicateQuery/ns1:predicate/ns1:assignmentFilter"/>
               </ns1:assignmentFilter>
               <ns1:predicate>
                  <ns1:logicalOperator>
                     <xsl:value-of select="/ns0:taskListRequest/ns1:taskPredicateQuery/ns1:predicate/ns1:predicate/ns1:logicalOperator"/>
                  </ns1:logicalOperator>
                  <ns1:clause>
                     <ns1:column tableName="{/ns0:taskListRequest/ns1:taskPredicateQuery/ns1:predicate/ns1:predicate/ns1:clause/ns1:column/@tableName}">
                        <ns1:columnName>
                           <xsl:value-of select="/ns0:taskListRequest/ns1:taskPredicateQuery/ns1:predicate/ns1:predicate/ns1:clause/ns1:column/ns1:columnName"/>
                        </ns1:columnName>
                     </ns1:column>
                     <ns1:operator>
                        <xsl:value-of select="/ns0:taskListRequest/ns1:taskPredicateQuery/ns1:predicate/ns1:predicate/ns1:clause/ns1:operator"/>
                     </ns1:operator>
                     <ns1:value>
                        <xsl:value-of select="/ns0:taskListRequest/ns1:taskPredicateQuery/ns1:predicate/ns1:predicate/ns1:clause/ns1:value"/>
                     </ns1:value>
                  </ns1:clause>
               </ns1:predicate>
            </ns1:predicate>
         </ns1:taskPredicateQuery>
      </ns0:taskListRequest>
   </xsl:template>
</xsl:stylesheet>
