<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/bpel/workflow/taskQueryService" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="https://test.com" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:task="http://xmlns.oracle.com/bpel/workflow/task"
                xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
                xmlns:ns2="http://xmlns.oracle.com/bpel/workflow/taskError"
                xmlns:ns3="http://xmlns.oracle.com/bpel/workflow/taskQueryService/schema"
                xmlns:common="http://xmlns.oracle.com/bpel/workflow/common"
                xmlns:user="http://xmlns.oracle.com/bpel/workflow/userMetadata"
                xmlns:ns1="http://xmlns.oracle.com/bpel/workflow/taskQuery"
                xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
                xmlns:ns4="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns5="http://xmlns.oracle.com/bpel/workflow/common/tsc"
                xmlns:ns6="http://oracle.com/sca/soapservice/AtradiusUtilityApplication/DashboardServices/FetchDashboardSOAPService"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns8="https://group.atradius1.com"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns7="https://group.atradius.com"
                xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/TaskQueryService_WSDL_TaskQueryServiceInterface.wsdl"/>
            <oracle-xsl-mapper:rootElement name="taskListResponse" namespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FetchDashboardSOAPServiceWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="root" namespace="https://test.com"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON SEP 11 15:40:35 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:root>
         <xsl:for-each select="/ns0:taskListResponse/task:task">
            <xsl:if test="task:payload">
               <tns:root2>
                  <tns:TaskStatus>
                     <xsl:value-of select="task:systemAttributes/task:state"/>
                  </tns:TaskStatus>
                  <xsl:copy-of select="task:payload"/>
               </tns:root2>
            </xsl:if>
         </xsl:for-each>
      </tns:root>
   </xsl:template>
</xsl:stylesheet>
