<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="https://test.com" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="https://group.atradius.com" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://oracle.com/sca/soapservice/AtradiusUtilityApplication/DashboardServices/FetchDashboardSOAPService"
                xmlns:ns2="https://group.atradius1.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FetchDashboardSOAPServiceWrapper.wsdl"/>
            <oracle-xsl-mapper:rootElement name="root" namespace="https://test.com"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FetchDashboardSOAPService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="processResponseTaskList" namespace="https://group.atradius.com"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON SEP 11 15:57:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:processResponseTaskList>
         <xsl:for-each select="/ns0:root/ns0:root2">
            <tns:TaxDutyBond>
               <tns:CustomerBond>
                  <tns:CustomerId>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerId"/>
                  </tns:CustomerId>
                  <tns:CustomerName>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerName"/>
                  </tns:CustomerName>
                  <tns:CustomerAddress>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerAddress"/>
                  </tns:CustomerAddress>
                  <tns:CustomerPostalCode>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerPostalCode"/>
                  </tns:CustomerPostalCode>
                  <tns:CustomerCity>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerCity"/>
                  </tns:CustomerCity>
                  <tns:CustomerCountry>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerCountry"/>
                  </tns:CustomerCountry>
                  <tns:CustomerVAT>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerVAT"/>
                  </tns:CustomerVAT>
                  <tns:CustomerStatus>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerStatus"/>
                  </tns:CustomerStatus>
                  <tns:CustomerContactName>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:CustomerContactName"/>
                  </tns:CustomerContactName>
                  <xsl:for-each select="ns0:payload/ns0:TaxDutyBond/ns0:CustomerBond/ns0:PolicyDtl">
                     <tns:PolicyDtl>
                        <tns:PolicyId>
                           <xsl:value-of select="ns0:PolicyId"/>
                        </tns:PolicyId>
                        <tns:CustomerId>
                           <xsl:value-of select="ns0:CustomerId"/>
                        </tns:CustomerId>
                        <tns:PolicyStatus>
                           <xsl:value-of select="ns0:PolicyStatus"/>
                        </tns:PolicyStatus>
                        <tns:PolicyIssueDate>
                           <xsl:value-of select="ns0:PolicyIssueDate"/>
                        </tns:PolicyIssueDate>
                        <tns:PolicyEffectiveDate>
                           <xsl:value-of select="ns0:PolicyEffectiveDate"/>
                        </tns:PolicyEffectiveDate>
                        <tns:PolicyCountry>
                           <xsl:value-of select="ns0:PolicyCountry"/>
                        </tns:PolicyCountry>
                        <tns:PolicyGeneralConditions>
                           <xsl:value-of select="ns0:PolicyGeneralConditions"/>
                        </tns:PolicyGeneralConditions>
                        <tns:PolicyParticularConditions>
                           <xsl:value-of select="ns0:PolicyParticularConditions"/>
                        </tns:PolicyParticularConditions>
                        <tns:PolicyNotice>
                           <xsl:value-of select="ns0:PolicyNotice"/>
                        </tns:PolicyNotice>
                        <xsl:for-each select="ns0:BondDtl">
                           <tns:BondDtl>
                              <tns:BondId>
                                 <xsl:value-of select="ns0:BondId"/>
                              </tns:BondId>
                              <tns:PolicyId>
                                 <xsl:value-of select="ns0:PolicyId"/>
                              </tns:PolicyId>
                              <tns:ProductId>
                                 <tns:ProductId>
                                    <xsl:value-of select="ns0:ProductId/ns0:ProductId"/>
                                 </tns:ProductId>
                                 <tns:BondClass>
                                    <xsl:value-of select="ns0:ProductId/ns0:BondClass"/>
                                 </tns:BondClass>
                                 <tns:Product>
                                    <xsl:value-of select="ns0:ProductId/ns0:Product"/>
                                 </tns:Product>
                                 <tns:BondStandardText>
                                    <xsl:value-of select="ns0:ProductId/ns0:BondStandardText"/>
                                 </tns:BondStandardText>
                                 <tns:BondCustomText>
                                    <xsl:value-of select="ns0:ProductId/ns0:BondCustomText"/>
                                 </tns:BondCustomText>
                                 <tns:BondAmount>
                                    <xsl:value-of select="ns0:ProductId/ns0:BondAmount"/>
                                 </tns:BondAmount>
                                 <tns:BondCurrency>
                                    <xsl:value-of select="ns0:ProductId/ns0:BondCurrency"/>
                                 </tns:BondCurrency>
                                 <tns:BondStartDate>
                                    <xsl:value-of select="ns0:ProductId/ns0:BondStartDate"/>
                                 </tns:BondStartDate>
                                 <tns:BondEndDate>
                                    <xsl:value-of select="ns0:ProductId/ns0:BondEndDate"/>
                                 </tns:BondEndDate>
                              </tns:ProductId>
                              <tns:BondStatus>
                                 <xsl:value-of select='oraext:query-database (concat ("select bond_status from bond where bond_id=", ns0:BondId ), false ( ), false ( ), "jdbc/BondDS" )'/>
                              </tns:BondStatus>
                              <tns:BondRequestDate>
                                 <xsl:value-of select="ns0:BondRequestDate"/>
                              </tns:BondRequestDate>
                              <tns:BondExposure>
                                 <xsl:value-of select="ns0:BondExposure"/>
                              </tns:BondExposure>
                              <tns:BondGroupingId>
                                 <xsl:value-of select="ns0:BondGroupingId"/>
                              </tns:BondGroupingId>
                              <tns:BondUWY>
                                 <xsl:value-of select="ns0:BondUWY"/>
                              </tns:BondUWY>
                              <tns:BondSpot>
                                 <xsl:value-of select="ns0:BondSpot"/>
                              </tns:BondSpot>
                              <tns:BondObligation>
                                 <xsl:value-of select="ns0:BondObligation"/>
                              </tns:BondObligation>
                              <tns:StandardDuration>
                                 <xsl:value-of select="ns0:StandardDuration"/>
                              </tns:StandardDuration>
                              <tns:BondNotice>
                                 <xsl:value-of select="ns0:BondNotice"/>
                              </tns:BondNotice>
                              <tns:BondType>
                                 <xsl:value-of select="ns0:BondType"/>
                              </tns:BondType>
                              <tns:BondCategory>
                                 <tns:BondSubCategory>
                                    <xsl:value-of select="ns0:BondCategory/ns0:BondSubCategory"/>
                                 </tns:BondSubCategory>
                              </tns:BondCategory>
                              <tns:Beneficiary>
                                 <tns:BeneficiaryId>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryId"/>
                                 </tns:BeneficiaryId>
                                 <tns:BeneficiaryCompanyName>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryCompanyName"/>
                                 </tns:BeneficiaryCompanyName>
                                 <tns:BeneficiaryFirstName>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryFirstName"/>
                                 </tns:BeneficiaryFirstName>
                                 <tns:BeneficiaryLastName>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryLastName"/>
                                 </tns:BeneficiaryLastName>
                                 <tns:BeneficiaryAddress>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryAddress"/>
                                 </tns:BeneficiaryAddress>
                                 <tns:BeneficiaryPostalCode>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryPostalCode"/>
                                 </tns:BeneficiaryPostalCode>
                                 <tns:BeneficiaryCity>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryCity"/>
                                 </tns:BeneficiaryCity>
                                 <tns:BeneficiaryCountry>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryCountry"/>
                                 </tns:BeneficiaryCountry>
                                 <tns:BeneficiaryVAT>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryVAT"/>
                                 </tns:BeneficiaryVAT>
                                 <tns:BeneficiaryGroupingId>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryGroupingId"/>
                                 </tns:BeneficiaryGroupingId>
                                 <tns:BeneficiaryStatus>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryStatus"/>
                                 </tns:BeneficiaryStatus>
                                 <tns:BeneficiaryContactName>
                                    <xsl:value-of select="ns0:Beneficiary/ns0:BeneficiaryContactName"/>
                                 </tns:BeneficiaryContactName>
                              </tns:Beneficiary>
                              <tns:Project>
                                 <tns:Specification>
                                    <xsl:value-of select="ns0:Project/ns0:Specification"/>
                                 </tns:Specification>
                                 <tns:Reference>
                                    <xsl:value-of select="ns0:Project/ns0:Reference"/>
                                 </tns:Reference>
                                 <tns:ExpectedDeliveryDate>
                                    <xsl:value-of select="ns0:Project/ns0:ExpectedDeliveryDate"/>
                                 </tns:ExpectedDeliveryDate>
                                 <tns:FixedExpiryDate>
                                    <xsl:value-of select="ns0:Project/ns0:FixedExpiryDate"/>
                                 </tns:FixedExpiryDate>
                                 <tns:ExpectedExpiryDate>
                                    <xsl:value-of select="ns0:Project/ns0:ExpectedExpiryDate"/>
                                 </tns:ExpectedExpiryDate>
                              </tns:Project>
                              <tns:Case>
                                 <tns:CaseId>
                                    <xsl:value-of select="ns0:Case/ns0:CaseId"/>
                                 </tns:CaseId>
                                 <tns:CaseSpecification>
                                    <xsl:value-of select="ns0:Case/ns0:CaseSpecification"/>
                                 </tns:CaseSpecification>
                                 <tns:CaseReference>
                                    <xsl:value-of select="ns0:Case/ns0:CaseReference"/>
                                 </tns:CaseReference>
                                 <tns:ExpectedDeliveryDate>
                                    <xsl:value-of select="ns0:Case/ns0:ExpectedDeliveryDate"/>
                                 </tns:ExpectedDeliveryDate>
                                 <tns:FixedExpiryDate>
                                    <xsl:value-of select="ns0:Case/ns0:FixedExpiryDate"/>
                                 </tns:FixedExpiryDate>
                                 <tns:ExpectedExpiryDate>
                                    <xsl:value-of select="ns0:Case/ns0:ExpectedExpiryDate"/>
                                 </tns:ExpectedExpiryDate>
                              </tns:Case>
                              <xsl:for-each select="ns0:Documents">
                                 <tns:Documents>
                                    <tns:DocumentId>
                                       <xsl:value-of select="ns0:DocumentId"/>
                                    </tns:DocumentId>
                                    <tns:BondId>
                                       <xsl:value-of select="ns0:BondId"/>
                                    </tns:BondId>
                                    <tns:Name>
                                       <xsl:value-of select="ns0:Name"/>
                                    </tns:Name>
                                    <tns:CreatedDate>
                                       <xsl:value-of select="ns0:CreatedDate"/>
                                    </tns:CreatedDate>
                                    <tns:Type>
                                       <xsl:value-of select="ns0:Type"/>
                                    </tns:Type>
                                    <tns:Link>
                                       <xsl:value-of select="ns0:Link"/>
                                    </tns:Link>
                                 </tns:Documents>
                              </xsl:for-each>
                           </tns:BondDtl>
                        </xsl:for-each>
                     </tns:PolicyDtl>
                  </xsl:for-each>
               </tns:CustomerBond>
               <tns:Analysis>
                  <tns:AnalysisId>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:AnalysisId"/>
                  </tns:AnalysisId>
                  <tns:BondId>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondId"/>
                  </tns:BondId>
                  <tns:CurrentBondingExposure>
                     <tns:GlobalBondingExposure>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:CurrentBondingExposure/ns0:GlobalBondingExposure"/>
                     </tns:GlobalBondingExposure>
                     <tns:BondClass>
                        <xsl:for-each select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:CurrentBondingExposure/ns0:BondClass/ns0:Product">
                           <tns:Product>
                              <tns:ProductName>
                                 <xsl:value-of select="ns0:ProductName"/>
                              </tns:ProductName>
                              <tns:ProductExposureAmount>
                                 <xsl:value-of select="ns0:ProductExposureAmount"/>
                              </tns:ProductExposureAmount>
                           </tns:Product>
                        </xsl:for-each>
                        <tns:ClassExposure>
                           <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:CurrentBondingExposure/ns0:BondClass/ns0:ClassExposure"/>
                        </tns:ClassExposure>
                     </tns:BondClass>
                  </tns:CurrentBondingExposure>
                  <tns:ReviewLimits>
                     <tns:CurrentReviewLimit>
                        <tns:GlobalRL>
                           <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:CurrentReviewLimit/ns0:GlobalRL"/>
                        </tns:GlobalRL>
                        <tns:NextReviewDate>
                           <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:CurrentReviewLimit/ns0:NextReviewDate"/>
                        </tns:NextReviewDate>
                        <xsl:for-each select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:CurrentReviewLimit/ns0:BondClass">
                           <tns:BondClass>
                              <xsl:for-each select="ns0:Product">
                                 <tns:Product>
                                    <tns:ProductName>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:CurrentReviewLimit/ns0:BondClass/ns0:Product/ns0:ProductName"/>
                                    </tns:ProductName>
                                    <tns:ProductReviewLimitAmount>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:CurrentReviewLimit/ns0:BondClass/ns0:Product/ns0:ProductReviewLimitAmount"/>
                                    </tns:ProductReviewLimitAmount>
                                 </tns:Product>
                              </xsl:for-each>
                              <tns:ClassReviewLimit>
                                 <xsl:value-of select="ns0:ClassReviewLimit"/>
                              </tns:ClassReviewLimit>
                           </tns:BondClass>
                        </xsl:for-each>
                     </tns:CurrentReviewLimit>
                     <tns:ProposedReviewLimit>
                        <tns:GlobalRL>
                           <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:ProposedReviewLimit/ns0:GlobalRL"/>
                        </tns:GlobalRL>
                        <tns:NextReviewDate>
                           <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:ProposedReviewLimit/ns0:NextReviewDate"/>
                        </tns:NextReviewDate>
                        <xsl:for-each select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:ProposedReviewLimit/ns0:BondClass">
                           <tns:BondClass>
                              <xsl:for-each select="ns0:Product">
                                 <tns:Product>
                                    <tns:ProductName>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:ProposedReviewLimit/ns0:BondClass/ns0:Product/ns0:ProductName"/>
                                    </tns:ProductName>
                                    <tns:ProductReviewLimitAmount>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:ReviewLimits/ns0:ProposedReviewLimit/ns0:BondClass/ns0:Product/ns0:ProductReviewLimitAmount"/>
                                    </tns:ProductReviewLimitAmount>
                                 </tns:Product>
                              </xsl:for-each>
                              <tns:ClassReviewLimit>
                                 <xsl:value-of select="ns0:ClassReviewLimit"/>
                              </tns:ClassReviewLimit>
                           </tns:BondClass>
                        </xsl:for-each>
                     </tns:ProposedReviewLimit>
                  </tns:ReviewLimits>
                  <tns:BondLineParameters>
                     <tns:CurrentBLP>
                        <tns:BondLineAmount>
                           <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:CurrentBLP/ns0:BondLineAmount"/>
                        </tns:BondLineAmount>
                        <xsl:for-each select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:CurrentBLP/ns0:BondClass">
                           <tns:BondClass>
                              <xsl:for-each select="ns0:Product">
                                 <tns:Product>
                                    <tns:ProductName>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:CurrentBLP/ns0:BondClass/ns0:Product/ns0:ProductName"/>
                                    </tns:ProductName>
                                    <tns:ProductBLSublimit>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:CurrentBLP/ns0:BondClass/ns0:Product/ns0:ProductBLSublimit"/>
                                    </tns:ProductBLSublimit>
                                    <tns:ProductMaxIndDuration>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:CurrentBLP/ns0:BondClass/ns0:Product/ns0:ProductMaxIndDuration"/>
                                    </tns:ProductMaxIndDuration>
                                    <tns:ProductMaxIndAmount>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:CurrentBLP/ns0:BondClass/ns0:Product/ns0:ProductMaxIndAmount"/>
                                    </tns:ProductMaxIndAmount>
                                    <tns:ProductSpecificBondText>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:CurrentBLP/ns0:BondClass/ns0:Product/ns0:ProductSpecificBondText"/>
                                    </tns:ProductSpecificBondText>
                                 </tns:Product>
                              </xsl:for-each>
                              <tns:ClassBLSublimit>
                                 <xsl:value-of select="ns0:ClassBLSublimit"/>
                              </tns:ClassBLSublimit>
                              <tns:ClassMaxIndAmount>
                                 <xsl:value-of select="ns0:ClassMaxIndAmount"/>
                              </tns:ClassMaxIndAmount>
                              <tns:ClassMaxIndDuration>
                                 <xsl:value-of select="ns0:ClassMaxIndDuration"/>
                              </tns:ClassMaxIndDuration>
                              <tns:ClassSpecificText>
                                 <xsl:value-of select="ns0:ClassSpecificText"/>
                              </tns:ClassSpecificText>
                           </tns:BondClass>
                        </xsl:for-each>
                     </tns:CurrentBLP>
                     <tns:ProposedBLP>
                        <tns:BondLineAmount>
                           <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:ProposedBLP/ns0:BondLineAmount"/>
                        </tns:BondLineAmount>
                        <xsl:for-each select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:ProposedBLP/ns0:BondClass">
                           <tns:BondClass>
                              <xsl:for-each select="ns0:Product">
                                 <tns:Product>
                                    <tns:ProductName>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:ProposedBLP/ns0:BondClass/ns0:Product/ns0:ProductName"/>
                                    </tns:ProductName>
                                    <tns:ProductBLSublimit>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:ProposedBLP/ns0:BondClass/ns0:Product/ns0:ProductBLSublimit"/>
                                    </tns:ProductBLSublimit>
                                    <tns:ProductMaxIndDuration>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:ProposedBLP/ns0:BondClass/ns0:Product/ns0:ProductMaxIndDuration"/>
                                    </tns:ProductMaxIndDuration>
                                    <tns:ProductMaxIndAmount>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:ProposedBLP/ns0:BondClass/ns0:Product/ns0:ProductMaxIndAmount"/>
                                    </tns:ProductMaxIndAmount>
                                    <tns:ProductSpecificBondText>
                                       <xsl:value-of select="/ns0:root/ns0:root2/ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:BondLineParameters/ns0:ProposedBLP/ns0:BondClass/ns0:Product/ns0:ProductSpecificBondText"/>
                                    </tns:ProductSpecificBondText>
                                 </tns:Product>
                              </xsl:for-each>
                              <tns:ClassBLSublimit>
                                 <xsl:value-of select="ns0:ClassBLSublimit"/>
                              </tns:ClassBLSublimit>
                              <tns:ClassMaxIndAmount>
                                 <xsl:value-of select="ns0:ClassMaxIndAmount"/>
                              </tns:ClassMaxIndAmount>
                              <tns:ClassMaxIndDuration>
                                 <xsl:value-of select="ns0:ClassMaxIndDuration"/>
                              </tns:ClassMaxIndDuration>
                              <tns:ClassSpecificText>
                                 <xsl:value-of select="ns0:ClassSpecificText"/>
                              </tns:ClassSpecificText>
                           </tns:BondClass>
                        </xsl:for-each>
                     </tns:ProposedBLP>
                  </tns:BondLineParameters>
                  <tns:EconomicalAnalysis>
                     <tns:CreationDate>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:CreationDate"/>
                     </tns:CreationDate>
                     <tns:LegalForm>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:LegalForm"/>
                     </tns:LegalForm>
                     <tns:ShareHolder>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:ShareHolder"/>
                     </tns:ShareHolder>
                     <tns:History>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:History"/>
                     </tns:History>
                     <tns:GroupActivity>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:GroupActivity"/>
                     </tns:GroupActivity>
                     <tns:MarketStudy>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:MarketStudy"/>
                     </tns:MarketStudy>
                     <tns:ExtraInfo>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:ExtraInfo"/>
                     </tns:ExtraInfo>
                     <tns:OpinionFinReports>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:OpinionFinReports"/>
                     </tns:OpinionFinReports>
                     <tns:OpinionFinElements>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:OpinionFinElements"/>
                     </tns:OpinionFinElements>
                     <tns:PerspectiveForNextPeriod>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:PerspectiveForNextPeriod"/>
                     </tns:PerspectiveForNextPeriod>
                     <tns:ProvisionalSales>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:ProvisionalSales"/>
                     </tns:ProvisionalSales>
                     <tns:InvestmentsAndProject>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:InvestmentsAndProject"/>
                     </tns:InvestmentsAndProject>
                     <tns:ExternalSources>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:ExternalSources"/>
                     </tns:ExternalSources>
                     <tns:Strengths>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:Strengths"/>
                     </tns:Strengths>
                     <tns:Weakness>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:EconomicalAnalysis/ns0:Weakness"/>
                     </tns:Weakness>
                  </tns:EconomicalAnalysis>
                  <tns:History>
                     <xsl:for-each select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:History/ns0:HistoryRow">
                        <tns:HistoryRow>
                           <tns:Decision>
                              <xsl:value-of select="ns0:Decision"/>
                           </tns:Decision>
                           <tns:Underwriter>
                              <xsl:value-of select="ns0:Underwriter"/>
                           </tns:Underwriter>
                           <tns:DecisionDate>
                              <xsl:value-of select="ns0:DecisionDate"/>
                           </tns:DecisionDate>
                        </tns:HistoryRow>
                     </xsl:for-each>
                  </tns:History>
                  <tns:UnderwriterOpinion>
                     <tns:ExposureComments>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:UnderwriterOpinion/ns0:ExposureComments"/>
                     </tns:ExposureComments>
                     <tns:Motive>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:UnderwriterOpinion/ns0:Motive"/>
                     </tns:Motive>
                     <tns:Decisions>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:UnderwriterOpinion/ns0:Decisions"/>
                     </tns:Decisions>
                     <tns:Conditions>
                        <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:UnderwriterOpinion/ns0:Conditions"/>
                     </tns:Conditions>
                  </tns:UnderwriterOpinion>
                  <tns:UserId>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:Analysis/ns0:UserId"/>
                  </tns:UserId>
               </tns:Analysis>
               <tns:AdditionalADFInputs>
                  <tns:UserId>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:AdditionalADFInputs/ns0:UserId"/>
                  </tns:UserId>
                  <tns:UserRole>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:AdditionalADFInputs/ns0:UserRole"/>
                  </tns:UserRole>
                  <tns:BondId>
                     <xsl:value-of select="ns0:payload/ns0:TaxDutyBond/ns0:AdditionalADFInputs/ns0:BondId"/>
                  </tns:BondId>
                  <tns:ButtonType>
                     <xsl:value-of select="ns0:TaskStatus"/>
                  </tns:ButtonType>
               </tns:AdditionalADFInputs>
            </tns:TaxDutyBond>
         </xsl:for-each>
      </tns:processResponseTaskList>
   </xsl:template>
</xsl:stylesheet>
