<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="TaskQueryService"
     targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:taskQueryService="http://xmlns.oracle.com/bpel/workflow/taskQueryService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="QueryTaskService">
        <plnk:role name="TaskQueryService" portType="taskQueryService:TaskQueryService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService" location="TaskQueryService.wsdl"/>
</wsdl:definitions>
